# Importando e coletando dados usando API

Aprenda a consumir dados através do uso de API.

In [ ]:
import requests
import pandas as pd

In [ ]:
indicador = requests.get('https://servicodados.ibge.gov.br/api/v1/paises/BR/indicadores/77830').json()

In [ ]:
indicador

[{'id': 77830,
  'indicador': 'Indicadores sociais - Esperança de vida ao nascer',
  'unidade': {'id': 'anos', 'classe': 'N', 'multiplicador': 1},
  'series': [{'pais': {'id': 'BR', 'nome': 'Brasil'},
    'serie': [{'-': None},
     {'1990': None},
     {'1990-1995': None},
     {'1995': None},
     {'1995-2000': None},
     {'1999-2001': None},
     {'2000': '69.737'},
     {'2000-2002': None},
     {'2000-2005': None},
     {'2001': '70.195'},
     {'2001-2003': None},
     {'2002': '70.41'},
     {'2002-2004': None},
     {'2003': '70.72'},
     {'2003-2005': None},
     {'2004': '71.131'},
     {'2004-2006': None},
     {'2005': '71.753'},
     {'2005-2007': None},
     {'2005-2010': None},
     {'2006': '72.037'},
     {'2006-2008': None},
     {'2007': '72.365'},
     {'2007-2009': None},
     {'2008': '72.715'},
     {'2008-2010': None},
     {'2009': '72.948'},
     {'2009-2011': None},
     {'2010': '73.182'},
     {'2010-2012': None},
     {'2010-2015': None},
     {'2011': '73.343'},
     {'2011-2013': None},
     {'2012': '73.552'},
     {'2012-2014': None},
     {'2013': '73.918'},
     {'2013-2015': None},
     {'2014': '74.306'},
     {'2014-2016': None},
     {'2015': '74.332'},
     {'2015-2017': None},
     {'2015-2020': None},
     {'2016': '74.442'},
     {'2016-2018': None},
     {'2017': '74.827'},
     {'2017-2019': None},
     {'2018': '75.109'},
     {'2018-2020': None},
     {'2019': '75.338'},
     {'2019-2021': None},
     {'2020': '74.009'},
     {'2020-2022': None},
     {'2021': '72.75'},
     {'2021-2023': None},
     {'2022': '73.425'},
     {'2022-2024': None},
     {'2023': None}]}]}]

In [ ]:
df_indicador = pd.DataFrame.from_dict(indicador[0]['series'][0]['serie'])

In [ ]:
df_limpo = df_indicador.dropna(axis=1, how='all')

In [ ]:
for col in df_limpo.columns:
    df_limpo[col] = pd.to_numeric(df_limpo[col], errors='coerce')

/tmp/ipython-input-6-3474855476.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_limpo[col] = pd.to_numeric(df_limpo[col], errors='coerce')

In [ ]:
mask_tem_valores = df_limpo.notna().any(axis=0)

In [ ]:
df_final = df_limpo.loc[:, mask_tem_valores]

In [ ]:
df_final.sample(10)

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,72.948,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,70.195,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,74.827,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Coletar todos os valores não nulos de todas as colunas
valores_reais = []
nomes_colunas = []

for coluna in df_final.columns:
    valores_nao_nulos = df_final[coluna].dropna()
    for valor in valores_nao_nulos:
        valores_reais.append(valor)
        nomes_colunas.append(f"{coluna}_{len([x for x in valores_reais if str(x).startswith(str(coluna))])}")

# Criar dataframe com uma única linha
df_uma_linha = pd.DataFrame([valores_reais], columns=nomes_colunas)

,2000_0,2001_0,2002_0,2003_0,2004_0,2005_0,2006_0,2007_0,2008_0,2009_0,...,2013_0,2014_0,2015_0,2016_0,2017_0,2018_0,2019_0,2020_0,2021_0,2022_0
0,69.737,70.195,70.41,70.72,71.131,71.753,72.037,72.365,72.715,72.948,...,73.918,74.306,74.332,74.442,74.827,75.109,75.338,74.009,72.75,73.425